[2023-09-29 18:07:53 +0000] [42665] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:443']
  backlog: 2048
  workers: 3
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /root/prod/trafficArbitrationForm/arb
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 0
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: ../access.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: ../error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: wsgi:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f1b468b5c60>
  on_reload: <function OnReload.on_reload at 0x7f1b468b5d80>
  when_ready: <function WhenReady.when_ready at 0x7f1b468b5ea0>
  pre_fork: <function Prefork.pre_fork at 0x7f1b468b5fc0>
  post_fork: <function Postfork.post_fork at 0x7f1b468b60e0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f1b468b6200>
  worker_int: <function WorkerInt.worker_int at 0x7f1b468b6320>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f1b468b6440>
  pre_exec: <function PreExec.pre_exec at 0x7f1b468b6560>
  pre_request: <function PreRequest.pre_request at 0x7f1b468b6680>
  post_request: <function PostRequest.post_request at 0x7f1b468b6710>
  child_exit: <function ChildExit.child_exit at 0x7f1b468b6830>
  worker_exit: <function WorkerExit.worker_exit at 0x7f1b468b6950>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f1b468b6a70>
  on_exit: <function OnExit.on_exit at 0x7f1b468b6b90>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: /etc/letsencrypt/live/credit-georgia.info/privkey.pem
  certfile: /etc/letsencrypt/live/credit-georgia.info/fullchain.pem
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-09-29 18:07:53 +0000] [42665] [INFO] Starting gunicorn 20.1.0
[2023-09-29 18:07:53 +0000] [42665] [DEBUG] Arbiter booted
[2023-09-29 18:07:53 +0000] [42665] [INFO] Listening at: https://0.0.0.0:443 (42665)
[2023-09-29 18:07:53 +0000] [42665] [INFO] Using worker: sync
[2023-09-29 18:07:53 +0000] [42666] [INFO] Booting worker with pid: 42666
[2023-09-29 18:07:53 +0000] [42666] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wsgi'
[2023-09-29 18:07:53 +0000] [42666] [INFO] Worker exiting (pid: 42666)
[2023-09-29 18:07:53 +0000] [42667] [INFO] Booting worker with pid: 42667
[2023-09-29 18:07:53 +0000] [42667] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wsgi'
[2023-09-29 18:07:53 +0000] [42667] [INFO] Worker exiting (pid: 42667)
[2023-09-29 18:07:53 +0000] [42665] [DEBUG] 3 workers
[2023-09-29 18:07:53 +0000] [42668] [INFO] Booting worker with pid: 42668
[2023-09-29 18:07:53 +0000] [42665] [WARNING] Worker with pid 42667 was terminated due to signal 15
[2023-09-29 18:07:53 +0000] [42668] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wsgi'
[2023-09-29 18:07:53 +0000] [42668] [INFO] Worker exiting (pid: 42668)
